//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace HDExportMetadataAndFile.DAO
{   
    public class INFORTAPE
    {    
        public long ID_CLIP { get; set; }
        public string MA_BANG { get; set; }
        public string TC_IN { get; set; }
        public string TC_OUT { get; set; }
        public string TL { get; set; }
        public int IS_SERVER { get; set; }
        public int IS_VTR { get; set; }
        public Nullable<int> IS_NAS { get; set; }
        public int PLAYTIME { get; set; }
        public string REAL_TC_IN { get; set; }
        public string REAL_TC_OUT { get; set; }
        public int TYPE { get; set; }
        public int NAS_ID_EDIT { get; set; }
        public int SECTION { get; set; }
        public string TEN_CHUONG_TRINH { get; set; }
        public string NOI_DUNG { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> RECORD_DATE { get; set; }
        public Nullable<int> TIME_TO_LIVE { get; set; }
        public Nullable<int> APPROVED { get; set; }
        public string COMMENT { get; set; }
        public Nullable<int> USERID { get; set; }
        public Nullable<int> SOURCE { get; set; }
        public Nullable<int> IS_RAW { get; set; }
        public Nullable<int> NAS_ID { get; set; }
        public string FILE_NAME { get; set; }
        public string HD_CLIP { get; set; }
        public Nullable<int> AFD_TYPE { get; set; }
        public string TEMPORARY_FILE_NAME { get; set; }
        public Nullable<int> SERVICE_LOW_RES_STATUS { get; set; }
        public Nullable<int> SERVICE_VOICE_OVER_STATUS { get; set; }
        public Nullable<int> SERVICE_SUBTITLE_STATUS { get; set; }
        public Nullable<int> SERVICE_REQUEST { get; set; }
        public Nullable<int> RTB_CHECKING { get; set; }
        public Nullable<int> NAS_ID_PREVIEW { get; set; }
        public Nullable<int> NAS_ID_TEMPORARY { get; set; }
        public Nullable<int> SERVICE_PRIORITY { get; set; }
        public string VERSION { get; set; }
        public string VIDEO_FORMAT { get; set; }
        public string TITLE_ORIGIN { get; set; }
        public Nullable<System.DateTime> START_RIGHTS { get; set; }
        public Nullable<System.DateTime> END_RIGHTS { get; set; }
        public string RUNS { get; set; }
        public string NOTE { get; set; }
        public Nullable<long> LTO_ID { get; set; }
        public Nullable<System.DateTime> LAST_ACCESSED_TIME { get; set; }
        public Nullable<double> AUDIO_LEVEL { get; set; }
        public Nullable<int> RAW_CHECK { get; set; }
        public string RAW_CHECK_NOTE { get; set; }
        public Nullable<int> USER_ID_RAW_CHECK { get; set; }
        public Nullable<int> USER_ID_DECIDE_SERVICE { get; set; }
        public Nullable<int> POST_QUALITY_CHECK { get; set; }
        public string POST_QUALITY_CHECK_NOTE { get; set; }
        public Nullable<int> USER_ID_POST_QUALITY_CHECK { get; set; }
        public Nullable<int> POST_CONTENT_VTV_CHECK { get; set; }
        public string POST_CONTENT_VTV_CHECK_NOTE { get; set; }
        public Nullable<int> USER_ID_POST_CONTENT_VTV_CHECK { get; set; }
        public Nullable<int> POST_CONTENT_VSTV_CHECK { get; set; }
        public string POST_CONTENT_VSTV_CHECK_NOTE { get; set; }
        public Nullable<int> USER_ID_POST_CONTENT_VSTV_CHECK { get; set; }
        public string KEYWORDS { get; set; }
        public Nullable<int> ORIGINAL_SERVICE_REQUEST { get; set; }
        public Nullable<int> USER_ID_RTB_CHECKING { get; set; }
        public Nullable<int> CAN_COPY { get; set; }
        public Nullable<int> CLIP_SOURCE_TYPE { get; set; }
        public string VERSION_FILE_DATE { get; set; }
        public string REASONABLE_SCENCES { get; set; }
        public string ASPECT_RATIO { get; set; }
        public string CODEC { get; set; }
        public Nullable<int> APPROVER_USER_ID { get; set; }
        public string APPROVER_COMMENT { get; set; }
        public Nullable<int> MASTER_CLIP_ID { get; set; }
        public Nullable<int> EPISODE_NUMBER { get; set; }
        public bool ALLOW_ARCHIVING { get; set; }
        public Nullable<int> POST_CHECK_SX { get; set; }
        public string POST_CHECK_SX_NOTE { get; set; }
        public Nullable<int> USER_ID_POST_CHECK_SX { get; set; }
        public Nullable<long> FILE_SIZE { get; set; }
        public string CODE { get; set; }
        public string THUMB_FRAME { get; set; }
        public Nullable<int> THUMB_CREAT_STATUS { get; set; }
        public string THUMB_FILE_NAME { get; set; }
        public Nullable<System.DateTime> SERVICE_LOW_RES_LAST_UPDATE { get; set; }
        public string TRANSCODING_ID { get; set; }
        public Nullable<System.DateTime> EXPIRATION_DATE { get; set; }
        public Nullable<long> IDPS { get; set; }
        public Nullable<int> Changed { get; set; }
        public Nullable<int> FILE_TRANS_STATUS { get; set; }
        public string RTB_CHECK_NOTE { get; set; }
        public Nullable<int> PROJECT_ID { get; set; }
        public Nullable<int> WORKFLOW_ID { get; set; }
        public Nullable<int> WORKFLOW_TYPE { get; set; }
        public Nullable<long> WORKFLOW_POST_ID { get; set; }
        public string LOGS { get; set; }
        public Nullable<int> SERVICE_TRANSCODE_STATUS { get; set; }
        public Nullable<int> NAS_ID_TKC { get; set; }
        public Nullable<int> ISSERVER_TKC { get; set; }
        public Nullable<int> SAFETY_POLICY { get; set; }
        public Nullable<System.DateTime> DATE_TO_BROADCAST { get; set; }
        public Nullable<int> SERVICE_EXPORT_STATUS { get; set; }
        public string EXPORT_FILE_NAME { get; set; }
        public Nullable<int> SERVICE_QC_STATUS { get; set; }
        public string SERVICE_QC_NOTE { get; set; }
        public Nullable<long> NEWS_ID { get; set; }
        public Nullable<int> SERVICE_TC_STATUS { get; set; }
        public System.Guid SyncId { get; set; }
        public Nullable<bool> ChangedFileTrans { get; set; }
        public Nullable<System.DateTime> SyncClipLastTime { get; set; }
        public int TryBackup { get; set; }
        public int TryOnAir { get; set; }
        public int TryEtere { get; set; }
        public string HIGH_RES_CHECKSUM { get; set; }
        public string APPROVE_HR_CHECKSUM { get; set; }
        public string MEDIA_INFOR_JSON { get; set; }
        public Nullable<long> PP_PROJECT_ID { get; set; }
        public Nullable<System.DateTime> SYNC_CLIP_LAST_TIME { get; set; }
        public Nullable<long> WORKFLOW_INSTANCE_ID { get; set; }
        public Nullable<int> Changed2 { get; set; }
        public Nullable<bool> ChangedFileTrans2 { get; set; }
        public Nullable<int> SERVICE_VERIFICATION_UPDATE_REQUEST { get; set; }
        public Nullable<long> SOURCE_MEDIA_ID { get; set; }
        public string DALET_EXTERSTRID { get; set; }
        public string DALET_COD_PROGRA { get; set; }
        public Nullable<bool> IS_DELETED { get; set; }          
    }
}
